  nginx:
    image: nginx
    ports:
      - 8089:80
    links:
      - php-fpm
    volumes:
      - /Users/yoga/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /Users/yoga/docker/nginx/vhost:/etc/nginx/vhost
      - /Users/yoga/www:/home/workspace
      - /Users/yoga/docker/www:/home/docker/www
  php-fpm:
    image: chunhei2008/php:phpunit
    mem_limit: 256M
    links:
      - memcached
      - redis
      - beanstalkd
      - mysql
    volumes:
      - /Users/yoga/docker/www:/home/docker/www
      - /Users/yoga/www:/home/workspace
      - /Users/yoga/docker/wwwlogs:/home/applogs
  memcached:
    image: memcached:1.4.31
    ports:
      - 11211:11211
  redis:
    image: redis
    ports:
      - 6379:6379
  beanstalkd:
    image: schickling/beanstalkd
    ports:
      - 11300:11300
  mysql:
    image: mysql
    volumes:
      - /Users/yoga/docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - 8088:80
    links:
      - mysql
