version: '2'

services:
  nginx:
    image: nginx
    ports:
      - 80:80
    depends_on:
      - php-fpm01
      - php-fpm02
      - php-fpm03
      - php-fpm04
      - php-fpm05
      - php-fpm06
      - php-fpm07
      - php-fpm08
      - php-fpm09
      - php-fpm10
    volumes:
      - /Users/yoga/docker/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /Users/yoga/docker/etc/nginx/vhost:/etc/nginx/vhost
      - /Users/yoga/docker/wwwlogs:/etc/nginx/logs
      - /Users/yoga/www:/home/workspace
      - /Users/yoga/docker/www:/home/docker/www
    networks:
      - default
  nginx01:
    image: nginx
    ports:
      - 8081:80
    depends_on:
      - php-fpm01
      - php-fpm02
      - php-fpm03
      - php-fpm04
      - php-fpm05
      - php-fpm06
      - php-fpm07
      - php-fpm08
      - php-fpm09
      - php-fpm10
    volumes:
      - /Users/yoga/docker/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /Users/yoga/docker/etc/nginx/vhost:/etc/nginx/vhost
      - /Users/yoga/docker/wwwlogs:/etc/nginx/logs
      - /Users/yoga/www:/home/workspace
      - /Users/yoga/docker/www:/home/docker/www
    networks:
      - default
  nginx02:
    image: nginx
    ports:
      - 8082:80
    depends_on:
      - php-fpm01
      - php-fpm02
      - php-fpm03
      - php-fpm04
      - php-fpm05
      - php-fpm06
      - php-fpm07
      - php-fpm08
      - php-fpm09
      - php-fpm10
    volumes:
      - /Users/yoga/docker/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /Users/yoga/docker/etc/nginx/vhost:/etc/nginx/vhost
      - /Users/yoga/docker/wwwlogs:/etc/nginx/logs
      - /Users/yoga/www:/home/workspace
      - /Users/yoga/docker/www:/home/docker/www
    networks:
      - default
  nginx03:
    image: nginx
    ports:
      - 8083:80
    depends_on:
      - php-fpm01
      - php-fpm02
      - php-fpm03
      - php-fpm04
      - php-fpm05
      - php-fpm06
      - php-fpm07
      - php-fpm08
      - php-fpm09
      - php-fpm10
    volumes:
      - /Users/yoga/docker/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /Users/yoga/docker/etc/nginx/vhost:/etc/nginx/vhost
      - /Users/yoga/docker/wwwlogs:/etc/nginx/logs
      - /Users/yoga/www:/home/workspace
      - /Users/yoga/docker/www:/home/docker/www
    networks:
      - default
  redis-4.0:
    image: chunhei2008/redis-docker:4.0
    ports:
      - 6379:6379
    volumes:
      - /Users/yoga/docker/etc/redis/4.0/redis.conf:/etc/redis/redis.conf
      - /Users/yoga/docker/redis/data/4.0:/data/
    networks:
      - default
  php-fpm01:
    image: chunhei2008/php:7.1-fpm
    volumes:
      - /Users/yoga/docker/www:/home/docker/www
      - /Users/yoga/www:/home/workspace
      - /Users/yoga/docker/wwwlogs:/home/applogs
      - /Users/yoga/docker/xhprof:/tmp/xhprof
      - /Users/yoga/docker/etc/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - default
  php-fpm02:
    image: chunhei2008/php:7.1-fpm
    volumes:
      - /Users/yoga/docker/www:/home/docker/www
      - /Users/yoga/www:/home/workspace
      - /Users/yoga/docker/wwwlogs:/home/applogs
      - /Users/yoga/docker/xhprof:/tmp/xhprof
      - /Users/yoga/docker/etc/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - default
  php-fpm03:
    image: chunhei2008/php:7.1-fpm
    volumes:
      - /Users/yoga/docker/www:/home/docker/www
      - /Users/yoga/www:/home/workspace
      - /Users/yoga/docker/wwwlogs:/home/applogs
      - /Users/yoga/docker/xhprof:/tmp/xhprof
      - /Users/yoga/docker/etc/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - default
  php-fpm04:
    image: chunhei2008/php:7.1-fpm
    volumes:
      - /Users/yoga/docker/www:/home/docker/www
      - /Users/yoga/www:/home/workspace
      - /Users/yoga/docker/wwwlogs:/home/applogs
      - /Users/yoga/docker/xhprof:/tmp/xhprof
      - /Users/yoga/docker/etc/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - default
  php-fpm05:
    image: chunhei2008/php:7.1-fpm
    volumes:
      - /Users/yoga/docker/www:/home/docker/www
      - /Users/yoga/www:/home/workspace
      - /Users/yoga/docker/wwwlogs:/home/applogs
      - /Users/yoga/docker/xhprof:/tmp/xhprof
      - /Users/yoga/docker/etc/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - default
  php-fpm06:
    image: chunhei2008/php:7.1-fpm
    volumes:
      - /Users/yoga/docker/www:/home/docker/www
      - /Users/yoga/www:/home/workspace
      - /Users/yoga/docker/wwwlogs:/home/applogs
      - /Users/yoga/docker/xhprof:/tmp/xhprof
      - /Users/yoga/docker/etc/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - default
  php-fpm07:
    image: chunhei2008/php:7.1-fpm
    volumes:
      - /Users/yoga/docker/www:/home/docker/www
      - /Users/yoga/www:/home/workspace
      - /Users/yoga/docker/wwwlogs:/home/applogs
      - /Users/yoga/docker/xhprof:/tmp/xhprof
      - /Users/yoga/docker/etc/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - default
  php-fpm08:
    image: chunhei2008/php:7.1-fpm
    volumes:
      - /Users/yoga/docker/www:/home/docker/www
      - /Users/yoga/www:/home/workspace
      - /Users/yoga/docker/wwwlogs:/home/applogs
      - /Users/yoga/docker/xhprof:/tmp/xhprof
      - /Users/yoga/docker/etc/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - default
  php-fpm09:
    image: chunhei2008/php:7.1-fpm
    volumes:
      - /Users/yoga/docker/www:/home/docker/www
      - /Users/yoga/www:/home/workspace
      - /Users/yoga/docker/wwwlogs:/home/applogs
      - /Users/yoga/docker/xhprof:/tmp/xhprof
      - /Users/yoga/docker/etc/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - default
  php-fpm10:
    image: chunhei2008/php:7.1-fpm
    volumes:
      - /Users/yoga/docker/www:/home/docker/www
      - /Users/yoga/www:/home/workspace
      - /Users/yoga/docker/wwwlogs:/home/applogs
      - /Users/yoga/docker/xhprof:/tmp/xhprof
      - /Users/yoga/docker/etc/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - default
  php-grpc:
    image: chunhei2008/php:7.1-grpc
    volumes:
      - /Users/yoga/www:/home/workspace
    networks:
      - default
networks:
  default:
    driver: bridge
