  nginx:
    image: nginx
    ports:
      - 8089:80
    links:
      - php-fpm
      - nginx01
      - nginx02
      - nginx03
      - php-fpm01
      - php-fpm02
      - php-fpm03
      - memcached  
    volumes:
      - /Users/yoga/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /Users/yoga/docker/nginx/vhost:/etc/nginx/vhost
      - /Users/yoga/docker/wwwlogs:/etc/nginx/logs
      - /Users/yoga/www:/home/workspace
      - /Users/yoga/docker/www:/home/docker/www
  php-fpm:
    image: chunhei2008/php:gd
    mem_limit: 1g
    links:
      - memcached
      - redis-master
      - redis-slave
      - beanstalkd
      - mysql
    volumes:
      - /Users/yoga/docker/www:/home/docker/www
      - /Users/yoga/www:/home/workspace
      - /Users/yoga/docker/wwwlogs:/home/applogs
  memcached:
    image: memcached:1.4.31
    ports:
      - 11211:11211
  redis-master:
    image: chunhei2008/redis:with-config
    ports:
      - 6379:6379
    volumes:
      - /Users/yoga/docker/redis/config/redis-master.conf:/etc/redis/redis.conf
      - /Users/yoga/docker/redis/data/master:/data/
  redis-slave:
    image: chunhei2008/redis:with-config
    ports:
      - 6380:6379
    links:
      - redis-master
    volumes:
      - /Users/yoga/docker/redis/config/redis-slave.conf:/etc/redis/redis.conf
      - /Users/yoga/docker/redis/data/slave:/data/
  beanstalkd:
    image: schickling/beanstalkd
    ports:
      - 11300:11300
  mysql:
    image: mysql
    volumes:
      - /Users/yoga/docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - 8088:80
    links:
      - mysql
  nginx01:
    image: nginx
    ports:
      - 8091:80
    links:
      - php-fpm
    volumes:
      - /Users/yoga/docker/nginx/nginx01.conf:/etc/nginx/nginx.conf
      - /Users/yoga/docker/nginx/vhost01:/etc/nginx/vhost01
      - /Users/yoga/www:/home/workspace
      - /Users/yoga/docker/www:/home/docker/www
  nginx02:
    image: nginx
    ports:
      - 8092:80
    links:
      - php-fpm
    volumes:
      - /Users/yoga/docker/nginx/nginx02.conf:/etc/nginx/nginx.conf
      - /Users/yoga/docker/nginx/vhost02:/etc/nginx/vhost02
      - /Users/yoga/www:/home/workspace
      - /Users/yoga/docker/www:/home/docker/www
  nginx03:
    image: nginx
    ports:
      - 8093:80
    links:
      - php-fpm
    volumes:
      - /Users/yoga/docker/nginx/nginx03.conf:/etc/nginx/nginx.conf
      - /Users/yoga/docker/nginx/vhost03:/etc/nginx/vhost03
      - /Users/yoga/www:/home/workspace
      - /Users/yoga/docker/www:/home/docker/www
  php-fpm01:
    image: chunhei2008/php:gd
    mem_limit: 1g
    links:
      - memcached
      - redis-master
      - redis-slave
      - beanstalkd
      - mysql
    volumes:
      - /Users/yoga/docker/www:/home/docker/www
      - /Users/yoga/www:/home/workspace
      - /Users/yoga/docker/wwwlogs:/home/applogs
  php-fpm02:
    image: chunhei2008/php:gd
    mem_limit: 1g
    links:
      - memcached
      - redis-master
      - redis-slave
      - beanstalkd
      - mysql
    volumes:
      - /Users/yoga/docker/www:/home/docker/www
      - /Users/yoga/www:/home/workspace
      - /Users/yoga/docker/wwwlogs:/home/applogs
  php-fpm03:
    image: chunhei2008/php:gd
    mem_limit: 1g
    links:
      - memcached
      - redis-master
      - redis-slave
      - beanstalkd
      - mysql
    volumes:
      - /Users/yoga/docker/www:/home/docker/www
      - /Users/yoga/www:/home/workspace
      - /Users/yoga/docker/wwwlogs:/home/applogs
