version: '2'

services:
  nginx:
    image: nginx
    ports:
      - 8089:80
    links:
      - php-fpm
      - nginx01
      - nginx02
      - nginx03
      - php-fpm01
      - php-fpm02
      - php-fpm03
      - memcached  
    volumes:
      - /Users/yoga/docker/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /Users/yoga/docker/etc/nginx/vhost:/etc/nginx/vhost
      - /Users/yoga/docker/wwwlogs:/etc/nginx/logs
      - /Users/yoga/www:/home/workspace
      - /Users/yoga/docker/www:/home/docker/www
    networks:
      - default
  php-fpm:
    image: chunhei2008/php:gd
    mem_limit: 1g
    links:
      - memcached
      - redis-master
      - redis-slave
      - beanstalkd
      - mysql-master
    volumes:
      - /Users/yoga/docker/www:/home/docker/www
      - /Users/yoga/www:/home/workspace
      - /Users/yoga/docker/wwwlogs:/home/applogs
    networks:
      - default
  memcached:
    image: memcached:1.4.31
    ports:
      - 11211:11211
    networks:
      - default
  redis-master:
    image: chunhei2008/redis:with-config
    ports:
      - 6379:6379
    volumes:
      - /Users/yoga/docker/etc/redis/redis-master.conf:/etc/redis/redis.conf
      - /Users/yoga/docker/redis/data/master:/data/
    networks:
      - default
  redis-slave:
    image: chunhei2008/redis:with-config
    ports:
      - 6380:6379
    links:
      - redis-master
    volumes:
      - /Users/yoga/docker/etc/redis/redis-slave.conf:/etc/redis/redis.conf
      - /Users/yoga/docker/redis/data/slave:/data/
    networks:
      - default
  beanstalkd:
    image: schickling/beanstalkd
    ports:
      - 11300:11300
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql-master
    ports:
      - 8088:80
    links:
      - mysql-master
    networks:
      - default
  nginx01:
    image: nginx
    ports:
      - 8091:80
    links:
      - php-fpm
    volumes:
      - /Users/yoga/docker/etc/nginx/nginx01.conf:/etc/nginx/nginx.conf
      - /Users/yoga/docker/etc/nginx/vhost01:/etc/nginx/vhost01
      - /Users/yoga/www:/home/workspace
      - /Users/yoga/docker/www:/home/docker/www
    networks:
      - default
  nginx02:
    image: nginx
    ports:
      - 8092:80
    links:
      - php-fpm
    volumes:
      - /Users/yoga/docker/etc/nginx/nginx02.conf:/etc/nginx/nginx.conf
      - /Users/yoga/docker/etc/nginx/vhost02:/etc/nginx/vhost02
      - /Users/yoga/www:/home/workspace
      - /Users/yoga/docker/www:/home/docker/www
    networks:
      - default
  nginx03:
    image: nginx
    ports:
      - 8093:80
    links:
      - php-fpm
    volumes:
      - /Users/yoga/docker/etc/nginx/nginx03.conf:/etc/nginx/nginx.conf
      - /Users/yoga/docker/etc/nginx/vhost03:/etc/nginx/vhost03
      - /Users/yoga/www:/home/workspace
      - /Users/yoga/docker/www:/home/docker/www
    networks:
      - default
  php-fpm01:
    image: chunhei2008/php:gd
    mem_limit: 1g
    links:
      - memcached
      - redis-master
      - redis-slave
      - beanstalkd
      - mysql-master
    volumes:
      - /Users/yoga/docker/www:/home/docker/www
      - /Users/yoga/www:/home/workspace
      - /Users/yoga/docker/wwwlogs:/home/applogs
    networks:
      - default
  php-fpm02:
    image: chunhei2008/php:gd
    mem_limit: 1g
    links:
      - memcached
      - redis-master
      - redis-slave
      - beanstalkd
      - mysql-master
    volumes:
      - /Users/yoga/docker/www:/home/docker/www
      - /Users/yoga/www:/home/workspace
      - /Users/yoga/docker/wwwlogs:/home/applogs
    networks:
      - default
  php-fpm03:
    image: chunhei2008/php:gd
    mem_limit: 1g
    links:
      - memcached
      - redis-master
      - redis-slave
      - beanstalkd
      - mysql-master
    volumes:
      - /Users/yoga/docker/www:/home/docker/www
      - /Users/yoga/www:/home/workspace
      - /Users/yoga/docker/wwwlogs:/home/applogs
    networks:
      - default
  mysql-master:
    image: mysql
    volumes:
      - /Users/yoga/docker/mysql/master:/var/lib/mysql
      - /Users/yoga/docker/etc/mysql/my-master.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
    networks:
      - default
  mysql-slave:
    image: mysql
    volumes:
      - /Users/yoga/docker/mysql/slave:/var/lib/mysql
      - /Users/yoga/docker/etc/mysql/my-slave.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3307:3306
    networks:
      - default
networks:
  default:
    driver: bridge
